### ISSUE TITLE
Pip installation failed

### ISSUE THREAD

**Issue by ZhaoJY1** [nussl/nussl#193]
**Describe the bug**
Windows 10
To install nussl using pip in conda env.

python 3.8.5 in a conda environment with pip 20.3
command `pip install nussl` get error output:
` Using cached gpytorch-0.2.0.tar.gz (169 kB)
    ERROR: Command errored out with exit status 1:
     command: 'D:\Anaconda\envs\music_source_separation_general\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\lenovo\\AppData\\Local\\Temp\\pip-install-affhr0p0\\gpytorch_d51182a0078142c8b63a596c1b32fb17\\setup.py'"'"'; __file__='"'"'C:\\Users\\lenovo\\AppData\\Local\\Temp\\pip-install-affhr0p0\\gpytorch_d51182a0078142c8b63a596c1b32fb17\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\lenovo\AppData\Local\Temp\pip-pip-egg-info-2vozllyb'
         cwd: C:\Users\lenovo\AppData\Local\Temp\pip-install-affhr0p0\gpytorch_d51182a0078142c8b63a596c1b32fb17\
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\lenovo\AppData\Local\Temp\pip-install-affhr0p0\gpytorch_d51182a0078142c8b63a596c1b32fb17\setup.py", line 40, in <module>
        with open("requirements.txt", "r") as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.`

**Comment by ZhaoJY1** [comment]
Still, I cannot regularly install `nussl` with `pip install nussl` and don't know the reason behind. So I decided to use `nussl` as a portable package, and tried to set up dependencies by `pip install -r requirements.txt`. But this command brings out errors, too. In my case (windows10, conda 4.9.2, python 3.8.5, pip 20.3), the main problem is to build `torch` and `pytorch-ignite`. So I removed these two packages in `requirements.txt` and then use `conda install pytorch` to install `torch` (because `torch` installation is included in `pytorch` installation in anaconda) later on. And after `torch` has been installed, use `pip install pytorch-ignite` to complete the installation of dependencies defined in original `requirements.txt` file.

But these have not get `imort nussl` to function normally for me yet. One problem is that in the `__init__.py` of module `stempeg` cound not find module `ffmpeg` or `ffprobe`, although I tried to use `pip` to install both modules to solve the problem. It seems in a conda environment, the code line in `__init__.py` of module `stempeg` to detect modules only find modules that also can be seen in Anaconda Navigator, because I used `conda install ffmpeg`, and problem solved.

Up to this position, `import nussl` in Jupyter-notebook has no problem.

But if I want to `import nussl` in a python IDE e.g. `Spyder`, it gives out an error saying `SoX not found`. So I followed the website suggestion to install `SoX` for my Windows and add it to system path as environment variable. Restart PC and everything works fine. (note: actually not everything works fine, my audio driver of PC cound not be found after system restart! Don't know whether related to installation of SoX, but follow repairing procedure of Windows Diagnose, Problem could be solved!)

Wrap up to a simple procedure that for me worked when I only want to use `nussl` as a portable package:
- remove `torch` and `pytorch-ignite` in `requirements.txt`
- `pip install -r requirements.txt`
- `conda install pytorch`
- `pip install pytorch-ignite`
- `conda install ffmpeg`
Then it should be able to be used in Jupyter-notebook.
For use with Python IDE:
- install SoX on Windows from [here](https://sourceforge.net/projects/sox/files/sox/) and add it to path.
- restart your PC
- if find problem with your audio driver, follow instructions of Windows Diagnose.
